In [1]:
import numpy as np
import torch
from transformers import AutoModelForCausalLM

from gptomics import gptneo, transformers

# Automatically rounding outputs to 4 digits
np.set_printoptions(precision=4)

/home/nt/miniconda3/envs/gpt-neo/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = transformers.load_model("EleutherAI/gpt-neo-125M")

In [3]:
t = torch.ones(1, 1, 768) * 1000

In [4]:
t = torch.ones(1, 1, 768) * 1
t2 = t * 2
t3 = t * 10

dvs = torch.cat((t, t2, t3), axis=1)

In [5]:
dvs.shape

torch.Size([1, 3, 768])

In [6]:
from torch.nn import functional as F

In [7]:
model.transformer.h[0].ln_1(dvs)[..., :10]

tensor([[[-0.1914,  0.5000, -0.0942,  0.0962,  0.2168, -0.0649, -0.1924,
           0.2256, -0.2930, -0.2539],
         [-0.1914,  0.5000, -0.0942,  0.0962,  0.2168, -0.0649, -0.1924,
           0.2256, -0.2930, -0.2539],
         [-0.1914,  0.5000, -0.0942,  0.0962,  0.2168, -0.0649, -0.1924,
           0.2256, -0.2930, -0.2539]]], grad_fn=<SliceBackward0>)

In [8]:
torch.layer_norm

<function _VariableFunctionsClass.layer_norm>

In [9]:
model.transformer.h[0].ln_1.bias[..., :10]

tensor([-0.1914,  0.5000, -0.0942,  0.0962,  0.2168, -0.0649, -0.1924,  0.2256,
        -0.2930, -0.2539], grad_fn=<SliceBackward0>)

In [10]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)>

In [11]:
def Ematrix(n, dtype=None):
    return np.eye(n, dtype=dtype) - 1/n

In [12]:
E = Ematrix(768)

In [13]:
np.linalg.norm(E[:, 1].ravel())

0.99934874626762

In [14]:
E

array([[ 0.9987, -0.0013, -0.0013, ..., -0.0013, -0.0013, -0.0013],
       [-0.0013,  0.9987, -0.0013, ..., -0.0013, -0.0013, -0.0013],
       [-0.0013, -0.0013,  0.9987, ..., -0.0013, -0.0013, -0.0013],
       ...,
       [-0.0013, -0.0013, -0.0013, ...,  0.9987, -0.0013, -0.0013],
       [-0.0013, -0.0013, -0.0013, ..., -0.0013,  0.9987, -0.0013],
       [-0.0013, -0.0013, -0.0013, ..., -0.0013, -0.0013,  0.9987]])